/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      fontFamily: {
        sans: "var(--font-sans)",
      },
      colors: {
        bg: "var(--c-app-bg)",
        background: "var(--c-background)",
        foreground: "var(--c-foreground)",
        surface: "var(--c-surface)",
        "surface-elevated": "var(--c-surface-elevated)",
        card: "var(--c-card)",
        "card-foreground": "var(--c-card-foreground)",
        popover: "var(--c-popover)",
        "popover-foreground": "var(--c-popover-foreground)",
        border: "var(--c-border)",
        input: "var(--c-input)",
        ring: "var(--c-ring)",
        primary: "var(--c-primary)",
        "primary-foreground": "var(--c-primary-foreground)",
        secondary: "var(--c-secondary)",
        "secondary-foreground": "var(--c-secondary-foreground)",
        accent: "var(--c-accent)",
        "accent-foreground": "var(--c-accent-foreground)",
        subtle: "var(--c-muted)",
        "muted-foreground": "var(--c-muted-foreground)",
        text: {
          primary: "var(--c-text-primary)",
          secondary: "var(--c-text-secondary)",
        },
        primaryText: "var(--c-text-primary)",
        secondaryText: "var(--c-text-secondary)",
        success: "var(--c-success)",
        warning: "var(--c-warning)",
        info: "var(--c-info)",
        danger: "var(--c-danger)",
        ink: "var(--c-product-text)",
        "ink-2": "var(--c-factor-text)",
        muted: "var(--c-muted-text)",
        focus: "var(--c-focus)",
        "status-success": "var(--c-status-success)",
        "status-error": "var(--c-status-error)",
        "status-warning": "var(--c-status-warning)",
        "status-info": "var(--c-status-info)",
        "grid-border": "var(--c-grid-border)",
        "grid-bg": "var(--c-grid-bg)",
        "grid-fill": "var(--c-grid-fill)",
        divider: "var(--c-divider)",
        "triangle-product": "var(--c-triangle-product)",
        "triangle-factor": "var(--c-triangle-factor)",
        "triangle-missing": "var(--c-triangle-missing)",
      },
      fontSize: {
        product: ["var(--fz-product)", { lineHeight: "var(--lh-product)" }],
        factor: ["var(--fz-factor)", { lineHeight: "var(--lh-factor)" }],
        operator: ["var(--fz-operator)", { lineHeight: "var(--lh-operator)" }],
        micro: ["var(--fz-micro)", { lineHeight: "var(--lh-micro)" }],
        "display-lg": ["3.75rem", { lineHeight: "1.1", letterSpacing: "-0.02em" }],
        display: ["3rem", { lineHeight: "1.15", letterSpacing: "-0.02em" }],
        "display-sm": ["2.25rem", { lineHeight: "1.2", letterSpacing: "-0.01em" }],
      },
      borderRadius: {
        swiss: "var(--radius-swiss)",
      },
      transitionTimingFunction: {
        swiss: "var(--ease-swiss)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        standard: "var(--duration-standard)",
      },
      maxWidth: {
        triangle: "var(--sz-triangle)",
      },
      width: {
        "structure-grid": "var(--sz-structure-grid)",
      },
      height: {
        "structure-grid": "var(--sz-structure-grid)",
      },
      minWidth: {
        touch: "var(--sz-touch)",
      },
      minHeight: {
        touch: "var(--sz-touch)",
      },
      boxShadow: {
        subtle: "var(--shadow-subtle)",
        elevated: "var(--shadow-elevated)",
        card: "var(--shadow-card)",
      },
    },
  },
};
