-- Supabase MVP schema + RLS

create extension if not exists "pgcrypto";

create table if not exists classes (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null,
  name text not null,
  join_code text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists classes_join_code_key on classes (join_code);
create index if not exists classes_teacher_id_idx on classes (teacher_id);

create table if not exists students (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references classes(id) on delete cascade,
  student_ref text not null,
  student_number integer not null,
  device_id text,
  created_at timestamptz not null default now()
);

create unique index if not exists students_class_ref_key on students (class_id, student_ref);
create unique index if not exists students_class_number_key on students (class_id, student_number);
create index if not exists students_class_idx on students (class_id);

create table if not exists student_events (
  id bigint generated by default as identity primary key,
  event_id text not null,
  class_id uuid not null references classes(id) on delete cascade,
  student_ref text not null,
  event_type text not null,
  event_ts bigint,
  session_id text,
  pack_id text,
  payload jsonb not null,
  server_received_at timestamptz not null default now()
);

create unique index if not exists student_events_event_id_key on student_events (event_id);
create index if not exists student_events_class_idx on student_events (class_id);
create index if not exists student_events_student_idx on student_events (student_ref);
create index if not exists student_events_type_idx on student_events (event_type);

create table if not exists task_end_events (
  id bigint generated by default as identity primary key,
  event_id text not null,
  class_id uuid not null references classes(id) on delete cascade,
  student_ref text not null,
  task_id text,
  session_id text,
  pack_id text,
  family_product integer not null,
  op text not null,
  missing text not null,
  locked_role text not null,
  attempts_before_end integer not null,
  used_structure_lens boolean not null,
  ms_to_end integer not null,
  result text not null,
  event_ts bigint,
  server_received_at timestamptz not null default now()
);

create unique index if not exists task_end_events_event_id_key on task_end_events (event_id);
create index if not exists task_end_events_class_idx on task_end_events (class_id);
create index if not exists task_end_events_product_idx on task_end_events (family_product);
create index if not exists task_end_events_result_idx on task_end_events (result);

alter table classes enable row level security;
alter table students enable row level security;
alter table student_events enable row level security;
alter table task_end_events enable row level security;

create policy "classes_select_own" on classes
  for select using (teacher_id = auth.uid());

create policy "classes_insert_own" on classes
  for insert with check (teacher_id = auth.uid());

create policy "classes_update_own" on classes
  for update using (teacher_id = auth.uid());

create policy "classes_delete_own" on classes
  for delete using (teacher_id = auth.uid());

create policy "students_select_by_teacher" on students
  for select using (
    exists (
      select 1 from classes c
      where c.id = students.class_id and c.teacher_id = auth.uid()
    )
  );

create policy "student_events_select_by_teacher" on student_events
  for select using (
    exists (
      select 1 from classes c
      where c.id = student_events.class_id and c.teacher_id = auth.uid()
    )
  );

create policy "task_end_events_select_by_teacher" on task_end_events
  for select using (
    exists (
      select 1 from classes c
      where c.id = task_end_events.class_id and c.teacher_id = auth.uid()
    )
  );
